name: Web Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  web_tests:
    runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.19.x', '1.21.x']

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: WillAbides/setup-go-faster@v1.8.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev

    - name: Build WebAssembly binary
      env:
        GOOS: js
        GOARCH: wasm
      working-directory: cmd/fyne_demo
      run: go build

    - name: Build WASM full website
      run: |
        go install ./cmd/fyne
        cd cmd/fyne_demo && fyne package --target=wasm
